DDCE-3896 Upgrade BRM to use jdk 11
hmrc/birth-registration-matching pull request #156
Opened 2023-03-28 14:40 UTC by gastonracui

# DDCE-???

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

## Checklist PR Raiser
- [ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
- [ ]  I've squashed my commits - including the JIRA issue number in the commit message
- [ ]  I've run a dependency check to ensure all dependencies are up to date

2023-03-31 15:50 UTC, stephenheath101 approved these changes

2023-04-03 10:41 UTC, stephenheath101 requested changes
Jenkins build is failing

2023-04-03 10:44 UTC, gastonracui commented
@stephenheath101 yes, thats because of flexmark upgrade as it needs to build with Java 11, the solution for this is merging build-jobs pr first, and then rerunning the checks here

2023-04-03 14:27 UTC, stephenheath101 approved these changes

2023-04-03 14:27 UTC, merged