BRMS-34 adding metrics class and unit tests
hmrc/birth-registration-matching pull request #25
Opened 2016-09-14 13:02 UTC by adamconder

- Adding metrics class and methods to time and status count connector.

2016-09-14 14:43 UTC, chris-ianson commented on app/uk/gov/hmrc/brm/metrics/Metrics.scala
> +  Seq(
@adamconder @manishsw 

Do we need to think about the key format/names? Do the keys below relate to the proxy response or the birth-registration-matching response to the consuming service?

2016-09-15 08:59 UTC, adamconder commented on app/uk/gov/hmrc/brm/metrics/Metrics.scala
> +  Seq(
@chris-ianson The keys below we're the responses from the proxy. We can add additional keys if necessary for the matching responses.

2016-09-15 12:41 UTC, adamconder commented
@chris-ianson I've updated the PR with additional test cases and now works across all connectors.

2016-09-15 12:57 UTC, chris-ianson commented on project/MicroServiceBuild.scala
> +  private val metricsGraphite = "3.0.2"
Remove metricsGraphite

2016-09-15 12:58 UTC, chris-ianson commented on project/MicroServiceBuild.scala
> +    "com.codahale.metrics" % "metrics-graphite" % metricsGraphite
Remove graphite

2016-09-15 13:02 UTC, chris-ianson commented on test/uk/gov/hmrc/brm/metrics/MetricsSpec/MetricsSpec.scala
> +      metrics.connectorStatus(404)
Ah, so we are a little more specific with error codes. Do you want us to log errors outside of 200, 400 and 500 (if applicable)

2016-09-15 13:02 UTC, chris-ianson requested changes
Looks great, just a couple of comments

2016-09-15 14:13 UTC, adamconder commented on test/uk/gov/hmrc/brm/metrics/MetricsSpec/MetricsSpec.scala
> +      metrics.connectorStatus(404)
@chris-ianson It would be useful if you log exceptions outside of 400 etc.

2016-09-15 14:18 UTC, adamconder commented on test/uk/gov/hmrc/brm/metrics/MetricsSpec/MetricsSpec.scala
> +      metrics.connectorStatus(404)
Updated these :)

2016-09-15 14:26 UTC, chris-ianson approved these changes

2016-09-15 14:26 UTC, merged