Brms 36 matching service
hmrc/birth-registration-matching pull request #33
Opened 2016-10-03 10:07 UTC by manishsw

updated with matching service and audit details to store in splunk for firstname, lastname and date of birth.

2016-10-04 07:23 UTC, chris-ianson commented on app/uk/gov/hmrc/brm/services/MatchingService.scala
> +  def performMatch(input: Payload, response: GroResponse, matchingType: MatchingType.Value): ResultMatch = {
Is it worth having a default for matchingType? If no value is passed it defaults to MatchingType.FULL

2016-10-04 15:32 UTC, adamconder commented on app/uk/gov/hmrc/brm/services/MatchingService.scala
> +  def performMatch(input: Payload, response: GroResponse, matchingType: MatchingType.Value): ResultMatch = {
@chris-ianson I would agree with that.

2016-10-04 15:56 UTC, adamconder requested changes

2016-10-04 15:56 UTC, adamconder commented on app/uk/gov/hmrc/brm/services/MatchingAlgorithm.scala
> +  private def getMatchResult(firstNames : Match, lastNames : Match,  dates: Match) : ResultMatch = {
@manishsw I'm going to refactor this method and remove it entirely.

2016-10-04 15:56 UTC, adamconder commented on app/uk/gov/hmrc/brm/services/MatchingService.scala
> +      case MatchingType.PARTIAL => PartialMatching
@manishsw I'm going to add a default case for this which is FullMatching

2016-10-05 10:41 UTC, adamconder approved these changes

2016-10-05 10:46 UTC, merged